apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: igc-nodejs
  labels:
    version: 0.0.0
spec:
  params:
    - name: git-url
    - name: git-revision
      default: master
    - name: image-url
  tasks:
    - name: test
      taskRef:
        name: igc-nodejs-test
      params:
        - name: git-url
          value: $(params.git-url)
        - name: git-revision
          value: $(params.git-revision)
    - name: build
      taskRef:
        name: igc-build-tag-push
      params:
        - name: git-url
          value: $(params.git-url)
        - name: git-revision
          value: $(tasks.test.results.git-commit)
        - name: image-url
          value: $(params.image-url)
