apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: ibm-mq
  annotations:
    app.openshift.io/runtime: mq
spec:
  params:
    - name: git-url
      description: The url for the git repository
    - name: git-revision
      description: The git revision (branch, tag, or sha) that should be built
      default: master
    - name: scan-image
      description: Enable the pipeline to scan the image for vulnerabilities
      default: "true"
    - name: lint-dockerfile
      description: Enable the pipeline to lint the Dockerfile for best practices
      default: "true"
  tasks:
    - name: setup
      taskRef:
        name: ibm-setup-v2-5-0
      params:
        - name: git-url
          value: $(params.git-url)
        - name: git-revision
          value: $(params.git-revision)
        - name: scan-image
          value: $(params.scan-image)
        - name: lint-dockerfile
          value: $(params.lint-dockerfile)
    - name: build
      taskRef:
        name: ibm-build-tag-push-v2-5-0
      runAfter:
        - setup
      params:
        - name: git-url
          value: "$(tasks.setup.results.git-url)"
        - name: git-revision
          value: "$(tasks.setup.results.git-revision)"
        - name: source-dir
          value: "$(tasks.setup.results.source-dir)"
        - name: image-server
          value: "$(tasks.setup.results.image-server)"
        - name: image-namespace
          value: "$(tasks.setup.results.image-namespace)"
        - name: image-repository
          value: "$(tasks.setup.results.image-repository)"
        - name: image-tag
          value: "$(tasks.setup.results.image-tag)"
    - name: deploy
      taskRef:
        name: ibm-deploy-v2-5-0
      runAfter:
        - build
      params:
        - name: git-url
          value: "$(tasks.setup.results.git-url)"
        - name: git-revision
          value: "$(tasks.setup.results.git-revision)"
        - name: source-dir
          value: "$(tasks.setup.results.source-dir)"
        - name: image-server
          value: "$(tasks.setup.results.image-server)"
        - name: image-namespace
          value: "$(tasks.setup.results.image-namespace)"
        - name: image-repository
          value: "$(tasks.setup.results.image-repository)"
        - name: image-tag
          value: "$(tasks.setup.results.image-tag)"
        - name: app-namespace
          value: "$(tasks.setup.results.app-namespace)"
        - name: app-name
          value: "$(tasks.setup.results.app-name)"
        - name: deploy-ingress-type
          value: "$(tasks.setup.results.deploy-ingress-type)"
        - name: tools-image
          value: "$(tasks.setup.results.tools-image)"
    - name: health
      taskRef:
        name: ibm-health-check-v2-5-0
      runAfter:
        - deploy
      params:
        - name: app-namespace
          value: "$(tasks.setup.results.app-namespace)"
        - name: app-name
          value: "$(tasks.setup.results.app-name)"
        - name: deploy-ingress-type
          value: "$(tasks.setup.results.deploy-ingress-type)"
        - name: health-protocol
          value: "$(tasks.setup.results.health-protocol)"
        - name: health-endpoint
          value: "$(tasks.setup.results.health-endpoint)"
        - name: health-url
          value: "$(tasks.setup.results.health-url)"
        - name: health-curl
          value: "$(tasks.setup.results.health-curl)"
        - name: tools-image
          value: "$(tasks.setup.results.tools-image)"
