name: Manual notify

on: 
  workflow_dispatch:
    inputs:
      slug:
        description: 'The remote repository'     
        required: true
        default: 'cloud-native-toolkit/terraform-tools-tekton-resources'

jobs:
  notify:
    runs-on: ubuntu-latest

    env:
      NOTIFY_SLUG: ${{ github.event.inputs.slug }}

    steps:
      - name: Publish repository dispatch
        run: |
          curl -XPOST -u "${{secrets.USERNAME}}:${{secrets.TOKEN}}" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/${{env.NOTIFY_SLUG}}/dispatches --data '{"event_type": "released"}'
